version: "3.8"

services:
     mysql:
          image: mysql:8.0
          container_name: now_mysql
          restart: always
          env_file:
               - ./.env
          environment:
               MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
               MYSQL_DATABASE: ${DB_DATABASE}
               MYSQL_USER: ${DB_USERNAME}
               MYSQL_PASSWORD: ${DB_PASSWORD}
          ports:
               - ${DB_PORT}:3306
          networks:
               - nowgoal_networks
          volumes:
               - ./docker/mysql:/var/lib/mysql

     phpmyadmin:
          image: phpmyadmin/phpmyadmin
          container_name: phpmyadmin_container
          restart: always
          environment:
               PMA_HOSTS: mysql
               PMA_PORT: 3306
               PMA_ARBITRARY: 1
          ports:
               - ${PMA_PORT}:80
          links:
               - mysql
          networks:
               - nowgoal_networks
          depends_on:
               - mysql
     app:
          build:
               context: ./docker/php
               dockerfile: Dockerfile
          container_name: now_app
          env_file:
               - ./.env
          volumes:
               - ./src:/var/www/html
          links:
               - mysql
          depends_on:
               - mysql
          environment:
               - DB_HOST=mysql
               - DB_DATABASE=${DB_DATABASE}
               - DB_USERNAME=${DB_USERNAME}
               - DB_PASSWORD=${DB_PASSWORD}
          networks:
               - nowgoal_networks
     nginx:
          image: nginx:latest
          container_name: now_nginx
          env_file:
               - ./.env
          ports:
               - ${APP_PORT}:80
          volumes:
               - ./src:/var/www/html
               - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          environment:
               - DB_HOST=mysql
               - DB_DATABASE=${DB_DATABASE}
               - DB_USERNAME=${DB_USERNAME}
               - DB_PASSWORD=${DB_PASSWORD}
          links:
               - app
               - mysql
          depends_on:
               - app
               - mysql
          networks:
               - nowgoal_networks
networks:
     nowgoal_networks:
          driver: bridge
